# see https://wiki.hypr.land/Hypr-Ecosystem/hyprlock

# set current colors
source = ~/.config/hypr/current_theme.conf

general {
    hide_cursor = true
}

animations {
    enabled = false
}

background {
    monitor =
    path = $HOME/Dotfiles/backgrounds/.config/backgrounds/current.png
    color = $base
    blur_passes = 1
}

input-field {
    monitor =

    fade_on_empty = false

    size = 15%, 5%

    outer_color = $overlay0
    outline_thickness = 3
    rounding = 5

    inner_color = $surface0

    font_color = $text
    font_family = JetBrainsMono Nerd Font
    placeholder_text = enter password
    dots_text_format = *
    dots_size = 0.3
    dots_spacing = 0.1

    capslock_color= $yellow
    numlock_color= $yellow
    bothlock_color= $yellow

    check_color = $blue

    fail_color = $red
    fail_text = $PAMFAIL
}
